# terraform.yml

name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11  # Replace with your desired Terraform version

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
   

    - name: Terraform Plan
      run: terraform plan -var-file="variables.tfvars"
      

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="variables.tfvars"
     

    - name: Terraform Show Outputs
      run: terraform show -json
      
